version: "3"

services:
  kaihole:
    image: pihole/pihole:latest
    container_name: kaihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "81:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: ${PASS}
      FTLCONF_CHECK_DISK: 0
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

